services:
  paprika-web:
    container_name: paprika-web
    build: .
    volumes:
      - "${PAPRIKA_DATA_DIR:-${HOME}/Library/Group Containers/72KVKW69K8.com.hindsightlabs.paprika.mac.v3/Data}:/paprika-data:ro"
    environment:
      - PAPRIKA_DATA_DIR=/paprika-data
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: nginx-dashboard_dashboard_net
